// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xezwkiadgqzbxmpmqxre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlendraWFkZ3F6YnhtcG1xeHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzU4NDMsImV4cCI6MjA3MDE1MTg0M30.8d59O1pTZGYFSHAkxPXjHRK4a5hibAjJBFhaLxjLxeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});